# Generated by Django 5.0.4 on 2024-05-04 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{17}$')]),
        ),
    ]
