# Generated by Django 5.0.4 on 2024-06-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_auth', '0004_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_full',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
