# Generated by Django 5.0.4 on 2024-05-03 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_address', models.CharField(max_length=42, unique=True, validators=[django.core.validators.RegexValidator(regex='^0x[a-fA-F0-9]{40}$')], verbose_name='smart contract address')),
                ('started', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('dispute', models.BooleanField(default=False)),
                ('time_creation', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
            ],
            options={
                'ordering': ['time_creation'],
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=2048)),
            ],
            options={
                'verbose_name_plural': 'Rules',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True, validators=[django.core.validators.RegexValidator(regex='^0x[a-fA-F0-9]{40}$')])),
            ],
        ),
    ]
