# Generated by Django 5.0.4 on 2024-05-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game',
            field=models.CharField(choices=[('CIV5', 'Civilization 5')], default=('CIV5', 'Civilization 5'), max_length=4),
        ),
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='duel', max_length=32),
            preserve_default=False,
        ),
    ]
