# Generated by Django 5.0.4 on 2024-05-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_game_game_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
