# Generated by Django 5.0.4 on 2024-05-17 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_player2'),
        ('steam_auth', '0004_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to='steam_auth.wallet'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_games', to='steam_auth.wallet'),
        ),
    ]
