# Generated by Django 5.0.4 on 2024-06-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_game_host_alter_game_player2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='sc_address',
        ),
        migrations.AddField(
            model_name='game',
            name='bet',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='game_index',
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='host_vote',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Voted'), (1, 'First Place'), (2, 'Second Place'), (3, 'Draw')], default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_vote',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Voted'), (1, 'First Place'), (2, 'Second Place'), (3, 'Draw')], default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='time_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
