# Generated by Django 5.0.4 on 2024-06-21 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_game_time_expire_game_play_period_and_more'),
        ('steam_auth', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_games', to='steam_auth.wallet'),
        ),
    ]
