# Generated by Django 5.0.4 on 2024-08-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game',
            field=models.CharField(choices=[('CHSS', 'Chess'), ('CIV5', 'Civilization 5'), ('CIV6', 'Civilization 6'), ('DOTA', 'Dota 2'), ('HRST', 'Hearthstone'), ('GWNT', 'Gwint')], default=('CHSS', 'Chess'), max_length=4),
        ),
    ]
